// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ShaSYlrIl6Ov7gZPA1aVj2-pDi0Qz6g',
    appId: '1:173777639539:android:4b571d315148e305efb206',
    messagingSenderId: '173777639539',
    projectId: 'example-6daae',
    databaseURL: 'https://example-6daae-default-rtdb.firebaseio.com',
    storageBucket: 'example-6daae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNf5MH119BHrJOjlIQ0pdM4Mz-fP5s5-8',
    appId: '1:173777639539:ios:bd93ae0bb227f7c5efb206',
    messagingSenderId: '173777639539',
    projectId: 'example-6daae',
    databaseURL: 'https://example-6daae-default-rtdb.firebaseio.com',
    storageBucket: 'example-6daae.appspot.com',
    iosBundleId: 'com.rollcake.firebaseExample',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa-U8GI0Fju_z-kgjG8o8mbEmuYbgxHD0',
    appId: '1:173777639539:web:9a18e026d94074baefb206',
    messagingSenderId: '173777639539',
    projectId: 'example-6daae',
    authDomain: 'example-6daae.firebaseapp.com',
    databaseURL: 'https://example-6daae-default-rtdb.firebaseio.com',
    storageBucket: 'example-6daae.appspot.com',
    measurementId: 'G-742Z46D33G',
  );

}